version: "3.3"

services:
  database:
    container_name: site-tayla_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/posgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=tlps2s2
      - POSTGRES_USER=site-tayla
    ports:
      - 5434:5432