version: "3.3"

services:
  database:
    container_name: site-tayla
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=site-tayla
      - POSTGRES_USER=site-tayla
    ports:
      - 5434:5432
