# Generated by Django 3.1.1 on 2020-09-14 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
