# Generated by Django 3.1.4 on 2021-02-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_formulario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
